/* Run against a local server. PLAYWRIGHT_MODULE may point to an installed module. */
const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base=process.env.TEST_BASE_URL || 'http://127.0.0.1:4173/';
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  try {
    const page=await browser.newPage({viewport:{width:1440,height:1060}});
    const errors=[],requests=[];
    page.on('pageerror',e=>errors.push(e.message));
    page.on('request',r=>requests.push(r.url()));
    page.on('response',r=>{if(r.status()>=400 && !r.url().endsWith('favicon.ico'))errors.push(`HTTP ${r.status()} ${r.url()}`);});
    await page.goto(base);
    await page.waitForSelector('.model-card');
    assert.equal(await page.locator('.model-card').count(),1);
    await page.screenshot({path:'tmp/home-desktop.png',fullPage:true});
    await page.locator('.model-card').click();
    await page.waitForSelector('.module-grid');
    await page.screenshot({path:'tmp/library-desktop.png',fullPage:false});
    assert.equal(requests.filter(url=>/\.pdf(?:\?|$)/.test(url)).length,0,'Browsing must not download PDF files');
    await page.locator('#search').fill('电瓶');
    await page.waitForFunction(()=>document.querySelector('.result-heading')?.textContent.includes('电瓶'));
    assert.ok((await page.locator('.document-row').first().innerText()).includes('蓄电池'));
    await page.screenshot({path:'tmp/search-desktop.png',fullPage:true});
    await page.locator('.document-row').first().click();
    await page.waitForSelector('.pdf-status[hidden]',{state:'attached',timeout:45000});
    assert.ok(await page.locator('#pdf-canvas').evaluate(el=>el.width>100));
    assert.ok(await page.locator('#pdf-text span').count()>0,'Selectable text layer must be present');
    await page.screenshot({path:'tmp/reader-desktop.png',fullPage:true});
    assert.equal(new Set(requests.filter(url=>/\.pdf(?:\?|$)/.test(url))).size,1);
    await page.locator('#next-page').click();
    await page.waitForFunction(()=>document.querySelector('#page-number')?.value==='2');
    await page.waitForSelector('.pdf-status[hidden]',{state:'attached'});
    await page.reload();
    await page.waitForSelector('.pdf-status[hidden]',{state:'attached',timeout:45000});
    assert.equal(await page.locator('#page-number').inputValue(),'2');
    await page.locator('#zoom-in').click();
    await page.waitForSelector('.pdf-status[hidden]',{state:'attached'});
    await page.locator('.reader-heading .back-link').click();
    await page.waitForSelector('#search');
    assert.equal(await page.locator('#search').inputValue(),'电瓶');
    await page.locator('#search').fill('P012B00');
    await page.waitForFunction(()=>document.querySelector('.document-row h3')?.textContent.includes('P012B00'));
    await page.locator('.document-row').first().click();
    await page.waitForSelector('.pdf-status[hidden]',{state:'attached',timeout:45000});
    await page.screenshot({path:'tmp/diagnostic-desktop.png',fullPage:true});
    await page.goto(base+'#/981/doc/981-3827?page=1');
    await page.waitForSelector('.pdf-status[hidden]',{state:'attached',timeout:45000});
    assert.ok((await page.locator('.related-docs').innerText()).includes('4455'));
    await page.goto(base+'#/981?q=发动鸡');
    await page.waitForSelector('.fuzzy-note');
    await page.goto(base+'#/981?module=4&q=P012B00');
    await page.waitForSelector('#search-all');
    await page.locator('#search-all').click();
    await page.waitForSelector('.document-row');
    await page.setViewportSize({width:390,height:844});
    await page.goto(base+'#/');
    await page.waitForSelector('.model-card');
    await page.screenshot({path:'tmp/home-mobile.png',fullPage:true});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Home mobile overflow');
    await page.locator('.model-card').click();
    await page.waitForSelector('.module-grid');
    await page.screenshot({path:'tmp/library-mobile.png',fullPage:false});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Library mobile overflow');
    await page.locator('#search').fill('火嘴');
    await page.waitForFunction(()=>document.querySelector('.document-row h3')?.textContent.includes('火花塞'));
    await page.locator('.document-row').first().click();
    await page.waitForSelector('.pdf-status[hidden]',{state:'attached',timeout:45000});
    await page.screenshot({path:'tmp/reader-mobile.png',fullPage:true});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Reader mobile overflow');
    assert.deepEqual(errors,[],'Browser runtime or network errors');
    assert.ok(requests.every(url=>url.startsWith(new URL(base).origin) || /^(data:|blob:)/.test(url)),'No external hosting dependency');
    console.log('PASS: desktop/mobile, lazy PDFs, aliases, typo fallback, module filter, DTC, text layer, paging, reload, zoom, continuation links, no external requests.');
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
