const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base=process.env.TEST_BASE_URL || 'http://127.0.0.1:4173/';
(async()=>{
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  try {
    const context=await browser.newContext({viewport:{width:1280,height:900},acceptDownloads:true});
    const page=await context.newPage();
    const errors=[],requests=[];
    page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
    const ready=n=>page.waitForSelector(`.pdf-sheet[data-page="${n}"][data-rendered="true"]`,{timeout:45000});
    const jump=async n=>{
      await page.locator('#page-number').fill(String(n));await page.locator('#page-number').press('Enter');await page.locator('#page-number').blur();
      await ready(n);
    };
    await page.goto(base+'#/981/doc/981-3827?page=1');
    await ready(1);
    assert.equal(await page.locator('.pdf-sheet').count(),5);
    assert.equal(await page.locator('#pdf-stage').evaluate(el=>getComputedStyle(el).maxHeight),'none');
    const movement=await page.locator('.pdf-sheet[data-page="2"]').evaluate(el=>el.getBoundingClientRect().top-document.querySelector('.reader-toolbar').offsetHeight-5);
    await page.mouse.wheel(0,movement);
    await page.waitForFunction(()=>document.querySelector('#page-number').value==='2');
    await ready(2);
    assert.ok(await page.evaluate(()=>scrollY>0));
    await jump(5);
    assert.equal(await page.locator('.pdf-sheet[data-page="5"]').getAttribute('data-doc'),'981-4455');
    assert.ok(page.url().includes('981-4455?page=1'));
    await page.reload();await ready(5);
    assert.equal(await page.locator('#page-number').inputValue(),'5');
    await page.screenshot({path:'tmp/continuous-desktop.png',fullPage:false});
    const download=page.waitForEvent('download');
    await page.locator('#download-project').click();
    await (await download).saveAs('tmp/merged-fuse-project.pdf');
    await page.waitForFunction(()=>!document.querySelector('#download-project').disabled);
    assert.ok((await page.locator('#download-status').innerText()).includes('5 页'));
    await page.goto(base+'#/981/doc/981-2117?page=1');await ready(1);
    assert.equal(await page.locator('.pdf-sheet').count(),128);
    await jump(90);
    assert.ok((await page.locator('.pdf-sheet[data-page="90"]').getAttribute('data-doc')).includes('2197'));
    assert.ok(await page.locator('.pdf-sheet canvas').count()<=6,'Canvas memory must remain bounded');
    assert.equal(await page.locator('.pdf-sheet[data-page="1"] canvas').count(),0);
    const before=await page.locator('.pdf-sheet[data-page="90"] canvas').evaluate(c=>c.getBoundingClientRect().width);
    await page.locator('#zoom-in').click();
    await page.waitForFunction(w=>{const c=document.querySelector('.pdf-sheet[data-page="90"] canvas');return c && c.getBoundingClientRect().width>w;},before);
    await ready(90);
    await page.locator('#fit-page').click();await ready(90);
    await jump(1);assert.ok(await page.locator('.pdf-sheet canvas').count()<=6);
    await page.goto(base+'#/981/doc/981-0099?page=1');await ready(1);
    assert.equal(await page.locator('.pdf-sheet').count(),2,'Other market variants must not be included');
    const single=page.waitForEvent('download');await page.locator('#download-project').click();await (await single).saveAs('tmp/single-market-project.pdf');
    await page.goto(base+'#/981/doc/981-3827?page=1');await ready(1);
    await context.route('**/docs/981/981-4455.pdf',r=>r.fulfill({status:503,body:'test failure'}));
    await page.locator('#download-project').click();
    await page.waitForSelector('#download-status.error',{timeout:30000});
    assert.ok(!(await page.locator('#download-project').isDisabled()));
    await context.unroute('**/docs/981/981-4455.pdf');
    const retry=page.waitForEvent('download');await page.locator('#download-project').click();await (await retry).saveAs('tmp/retried-project.pdf');
    await page.setViewportSize({width:390,height:844});
    await page.goto(base+'#/981/doc/981-3827?page=1');await ready(1);
    await page.waitForFunction(()=>{const c=document.querySelector('.pdf-sheet[data-page="1"] canvas');return c && c.getBoundingClientRect().width<=innerWidth;});
    await ready(1);
    await page.screenshot({path:'tmp/continuous-mobile-top.png',fullPage:false});
    const mobileMovement=await page.locator('.pdf-sheet[data-page="3"]').evaluate(el=>el.getBoundingClientRect().top-document.querySelector('.reader-toolbar').offsetHeight-5);
    await page.mouse.wheel(0,mobileMovement);await ready(3);
    await page.waitForFunction(()=>Number(document.querySelector('#page-number').value)>=2);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:'tmp/continuous-mobile-scroll.png',fullPage:false});
    await page.locator('.reader-bottom a').scrollIntoViewIfNeeded();await page.locator('.reader-bottom a').click();
    await page.waitForSelector('#search');
    assert.deepEqual(errors,[]);
    assert.ok(requests.every(x=>x.startsWith(new URL(base).origin)||/^(blob:|data:)/.test(x)));
    console.log('PASS: natural scrolling, continuation chaining, 128-page virtualization, deep-link restore, zoom, mobile scroll, full-project download, variant isolation, download failure/retry.');
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
